package com.jfsoft.interfaces.webservice.client;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-31T17:20:56.309+08:00
 * Generated source version: 3.2.12
 *
 */
@WebServiceClient(name = "DemoServiceImplService",
                  wsdlLocation = "http://10.0.2.72:9008/webservice/demo?wsdl",
                  targetNamespace = "http://service.business.interfaces.jfsoft.com/")
public class DemoServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.business.interfaces.jfsoft.com/", "DemoServiceImplService");
    public final static QName DemoServiceImplPort = new QName("http://service.business.interfaces.jfsoft.com/", "DemoServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.0.2.72:9008/webservice/demo?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DemoServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://10.0.2.72:9008/webservice/demo?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DemoServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DemoServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DemoServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DemoServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IDemoService
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public IDemoService getDemoServiceImplPort() {
        return super.getPort(DemoServiceImplPort, IDemoService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDemoService
     */
    @WebEndpoint(name = "DemoServiceImplPort")
    public IDemoService getDemoServiceImplPort(WebServiceFeature... features) {
        return super.getPort(DemoServiceImplPort, IDemoService.class, features);
    }

}
