package com.jfsoft.interfaces.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-31T17:20:56.303+08:00
 * Generated source version: 3.2.12
 *
 */
@WebService(targetNamespace = "http://service.business.interfaces.jfsoft.com/", name = "IDemoService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDemoService {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.business.interfaces.jfsoft.com/", className = "com.jfsoft.interfaces.webservice.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.business.interfaces.jfsoft.com/", className = "com.jfsoft.interfaces.webservice.client.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String hello(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0
    );
}
