
package com.jfsoft.interfaces.webservice.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.12
 * 2020-03-31T17:20:56.259+08:00
 * Generated source version: 3.2.12
 *
 */
public final class IDemoService_DemoServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.business.interfaces.jfsoft.com/", "DemoServiceImplService");

    private IDemoService_DemoServiceImplPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = DemoServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        DemoServiceImplService ss = new DemoServiceImplService(wsdlURL, SERVICE_NAME);
        IDemoService port = ss.getDemoServiceImplPort();

        {
        System.out.println("Invoking hello...");
        String _hello_arg0 = "";
        String _hello__return = port.hello(_hello_arg0);
        System.out.println("hello.result=" + _hello__return);


        }

        System.exit(0);
    }

}
